import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Header() {
    return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={styles.header}>
            <div>
                こんにちは！
            </div>
        </header>
    </>
    );
}