import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Sidebar from "../components/sidebar";
import Fab from '@mui/material/Fab';
import AddIcon from '@mui/icons-material/Add';

    export default function User() {
    // const data = [
    //     {
    //     id: "id_1",
    //     name: "user1",
    //     email: "user1@com",
    //     genre: "管理者",
    //     },
    //     {
    //     id: "id_2",
    //     name: "user2",
    //     email: "user2@com",
    //     genre: "ユーザー",
    //     },
    //     {
    //     id: "id_3",
    //     name: "user3",
    //     email: "user3@com",
    //     genre: "ユーザー",
    //     },
    // ];

    return (
        <>
        <div>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <div className={styles.flex}>
            <Sidebar />
            <main className={styles.main2}>
                <table className={styles.table}>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>名前</th>
                        <th>誕生日</th>
                        <th>性別</th>
                        <th>メール</th>
                        <th>職種</th>
                        <th>登録日</th>
                    </tr>
                </thead>
                <tbody>
                    {/* {data.map((value, key) => {
                    return (
                        <tr key={key}>
                        <td className="border px-4 py-2">{value.id}</td>
                        <td className="border px-4 py-2">{value.name}</td>
                        <td className="border px-4 py-2">{value.email}</td>
                        <td className="border px-4 py-2">{value.genre}</td>
                        </tr>
                    );
                    })} */}
                </tbody>
                </table>
                <Link href="/user_create">
                <Fab color="primary" aria-label="add" className={styles.addButton}>
                    <AddIcon />
                </Fab>
                </Link>
            </main>
            </div>
        </div>
        </>
    );
};