import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Sidebar from "../components/sidebar";
import { Fab } from "@mui/material";
import * as React from 'react';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select, { SelectChangeEvent } from '@mui/material/Select';

export default function User_Create() {
    const [sex, setSex] = React.useState('');
    const handleChange = () => {
    setAge(event.target.value);
    };

    return (
        <>
        <div>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <div className={styles.flex}>
                <Sidebar />
            <main className={styles.main}>
                <table>
                    <th>名前</th>
                <FormControl sx={{ m: 1, minWidth: 120 }} size="small">
                    <InputLabel id="demo-select-small">性別</InputLabel>
                    <Select
                        labelId="demo-select-small"
                        id="demo-select-small"
                        value={sex}
                        label="Age"
                        onChange={handleChange}
                    >
                        <MenuItem value="">
                        <em>None</em>
                        </MenuItem>
                        <MenuItem value={10}>男性</MenuItem>
                        <MenuItem value={20}>女性</MenuItem>
                        <MenuItem value={30}>その他</MenuItem>
                    </Select>
                </FormControl>
                </table>
        </main>
        </div>
        </div>
        </>
    );
    };